#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys

/sbin/mdev -s

echo "------------------------------------------------"
echo "  Welcome to Linux "
echo "------------------------------------------------"
